### ISSUE TITLE
Mybet

### ISSUE THREAD

**Issue by EltarSilence** [EltarSilence/Quoting_System-3#1]
Bug nel sistema
File: controller.php @ riga 216.

Con quell'istruzione, le scommesse in my-bet vengono visualizzate **sempre aperte**. Senza, se sono aperte vengono visualizzate perdenti, e nei restanti casi correttamente.
Fatto sta che, l'attributo _isWon_ degli oggetti delle scommesse e' sempre **-1**, fatto che le rende aperte.
Probabilmente il problema si trova nel controller, e non nel my-bet.

Inoltre non funziona il pagamento automatico della schedina una volta valutata vincente.

**Comment by Zexal0807** [comment]
Sistemato
